# -*- coding: utf-8 -*-
"""Clean jobs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mA5JCPLIZ1QqYJ5E72GkeCrao-S_dz5k
"""

import pandas as pd
import numpy as np


df = pd.read_csv("/content/jobs.csv")
df.head()

import re

def normalize_title(title):
    title = str(title).lower()

    # remove brackets containing contract info
    title = re.sub(r"\([^)]*contract[^)]*\)", "", title)

    # remove trailing contract phrases
    title = re.sub(r"\b\d+\s*[-]?\s*month[s]?\s*contract\b", "", title)
    title = re.sub(r"\bone\s*year\s*contract\b", "", title)
    title = re.sub(r"\bcontract\b", "", title)

    title = re.sub(r"\[.*?\]", "", title)      # [Job Code ...]
    title = re.sub(r"\(jd#.*?\)", "", title, flags=re.I)
    title = re.sub(r"\|\s*up.*$", "", title, flags=re.I)

    # remove permanent / perm labels
    title = re.sub(r"\bpermanent\b", "", title)
    title = re.sub(r"\bperm\b", "", title)

    # remove anything in brackets
    title = re.sub(r"\(.*?\)", "", title)

    # remove anything after dash
    title = re.sub(r"\s+-\s+.*$", "", title)

    # collapse whitespace
    title = " ".join(title.split())

    # title case
    title = title.title()

    return title

def job_family(title):

    title = title.lower()

    if "data engineer" in title:
        return "Data Engineer"

    if "data scientist" in title:
        return "Data Scientist"

    if "data analyst" in title:
        return "Data Analyst"

    if "machine learning" in title:
        return "Machine Learning Engineer"

    if "data architect" in title:
        return "Data Architect"

    if "data governance" in title:
        return "Data Governance"

    return title


def fix_acronyms(title):

    replacements = {
        "Ai": "AI",
        "Sql": "SQL",
        "Aws": "AWS",
        "Vp": "VP",
        "It": "IT",
        "Ml": "ML",
        "Bi": "BI",
        "Etl": "ETL",
        "Api": "API",
        "Qa": "QA",
        "Cib": "CIB",
        "Sap": "SAP",
        "Dcsmc": "DCSMC",
        "Wph": "WPH",
        "Imc": "IMC",
        "Smai":"SMAI"
    }

    for old, new in replacements.items():
        title = title.replace(old, new)

    return title

df["title_norm"] = df["title"].apply(normalize_title)

df["title_clean"] = (
    df["title_norm"]
    .apply(job_family)
    .str.strip()
    .str.title()
    .apply(fix_acronyms)
)

df.info()

df.head()

import ast

def combine_skills(series):
    skills = set()

    for item in series:
        try:
            if isinstance(item, str):
                item = ast.literal_eval(item)

            skills.update(item)

        except:
            pass

    return sorted(skills)

def combine_companies(series):
    return sorted(series.dropna().unique())

def combine_descriptions(series):
    return " ".join(series.dropna().astype(str))

df_roles = (
    df.groupby("title_clean")
      .agg(
          job_count=("title", "count"),
          salary_min=("salary_min", "min"),
          salary_max=("salary_max", "max"),
          skills=("skills", combine_skills),
          companies=("company", combine_companies),
          job_text=("description", combine_descriptions)
      )
      .reset_index()
)

df_roles = df_roles.rename(columns={
    "company": "companies",
    "description": "job_text"
})
df_roles["company_count"] = df_roles["companies"].apply(len)
df_roles["skill_count"] = df_roles["skills"].apply(len)

df_roles.sort_values("job_count", ascending=False)[
    ["title_clean", "job_count", "company_count", "skill_count"]
].head(20)

df_roles.to_csv("jobs_clean.csv", index=False)