# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZMFWfBNHxOw0fb6OYnMViUgcUiYgk7R
"""

from openai import OpenAI
import pandas as pd
import pickle
import ast

from getpass import getpass
from openai import OpenAI

api_key = getpass("Enter your OpenAI API key: ")

client = OpenAI(api_key=api_key)

jobs = pd.read_csv("jobs_clean.csv")

def safe_literal_eval(x):
    try:
        return ast.literal_eval(x)
    except:
        return []

jobs["skills"] = jobs["skills"].apply(safe_literal_eval)

jobs["companies"] = jobs["companies"].apply(ast.literal_eval)

documents = []

for _, row in jobs.iterrows():

    doc = f"""
    Role: {row['title_clean']}

    Skills:
    {', '.join(row['skills'])}

    Salary:
    ${row['salary_min']} - ${row['salary_max']}

    Employers:
    {', '.join(row['companies'])}

    """

    documents.append(doc)

print(documents[0])

for i, doc in enumerate(documents):
    if len(doc.split()) > 5000:
        print(i, len(doc.split()))

response = client.embeddings.create(
    model="text-embedding-3-small",
    input=documents
)

vectors = [
    item.embedding
    for item in response.data
]


with open("role_embeddings.pkl", "wb") as f:
    pickle.dump(
        {
            "documents": documents,
            "vectors": vectors,
            "roles": jobs["title_clean"].tolist()
        },
        f
    )

courses = pd.read_csv("courses.csv")

courses.head(5)

def clean_skills(x):
    if pd.isna(x):
        return []

    # remove weird encoding
    x = x.replace("_x000D_", "")
    x = x.replace("â€™", "'")

    # split bullets
    skills = [
        s.strip("* ").strip()
        for s in x.split("\n")
        if s.strip()
    ]

    return skills


courses["skills"] = courses["skills"].apply(clean_skills)

documents = []

for _, row in courses.iterrows():

    doc = f"""
    Course: {row['course']}

    Skills:
    {', '.join(row['skills'])}

    Provider:
    {row['provider']}

    Fee:
    ${row['fee']}
    """

    documents.append(doc)

print(documents[0])

response = client.embeddings.create(
    model="text-embedding-3-small",
    input=documents
)

vectors = [
    item.embedding
    for item in response.data
]


with open("course_embeddings.pkl", "wb") as f:
    pickle.dump(
        {
            "documents": documents,
            "vectors": vectors,
            "course": courses["course"].tolist()
        },
        f
    )