# -*- coding: utf-8 -*-
"""Extract jobs and courses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbMaNydyBXziFx2A6zoyJAJd7wlQep0l
"""

import requests
import pandas as pd
import time

!pip install beautifulsoup4

"""# Setup MyCareersFuture API"""

url = "https://api.mycareersfuture.gov.sg/v2/jobs"

params = {
    "search": "data",   # keyword
    "page": 0,
    "size": 20
}

r = requests.get(url, params=params)
data = r.json()

print(data.keys())

"""## Extract Job Listings"""

from bs4 import BeautifulSoup

num_pages = 20
all_jobs = []

for page in range(num_pages):
    params = {
        "search": "data",
        "page": page,
        "size": 20
    }

    r = requests.get(url, params=params)
    results = r.json().get("results", [])

    for j in results:
        skills = []
        for skill in j.get('skills'):
            skills.append(skill.get('skill'))


        html = j.get("description")
        soup = BeautifulSoup(html, "html.parser")
        clean_desc = soup.get_text()

        all_jobs.append({"title": j.get("title"),
                         "company": j.get("postedCompany")['name'],
                         "salary_min": j.get("salary")['minimum'],
                         "salary_max": j.get("salary")['maximum'],
                         "skills": skills,
                         "description": clean_desc
                         })

    time.sleep(0.5)  # be polite

df_jobs = pd.DataFrame(all_jobs)
print(len(df_jobs))
df_jobs.head()

df_jobs.info()

df_jobs.to_csv("./data/jobs.csv", index=False)



"""#Setup SkillsFuture API"""

import io

dataset_id = "d_b5802b76f409764c16dde4bf2feb19cd"

api_url = f"https://api-open.data.gov.sg/v1/public/api/datasets/{dataset_id}/poll-download"

json_data = requests.get(api_url).json()

download_url = json_data["data"]["url"]

file_resp = requests.get(download_url)

df = pd.read_excel(io.BytesIO(file_resp.content), engine="openpyxl")

df.head()

df_courses = df.head(20)[
    ["coursetitle", "trainingprovideralias", "full_course_fee", "what_you_learn"]
].rename(columns={
    "coursetitle": "course",
    "trainingprovideralias": "provider",
    "full_course_fee": "fee",
    "what_you_learn": "skills"
})

df_courses.head()

df_courses['skills'][0]

df_courses.to_csv("./data/courses.csv", index=False)