# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZMFWfBNHxOw0fb6OYnMViUgcUiYgk7R
"""

from openai import OpenAI
import pandas as pd
import pickle

from getpass import getpass
from openai import OpenAI

api_key = getpass("Enter your OpenAI API key: ")

client = OpenAI(api_key=api_key)

jobs = pd.read_csv("jobs_clean.csv")

jobs["skills_embedding"] = jobs["skills"].apply(
    lambda x: x[:50]
)

documents = []

for _, row in jobs.iterrows():

    doc = f"""
    Role: {row['title_clean']}

    Skills:
    {', '.join(row['skills_embedding'])}

    Salary:
    ${row['salary_min']} - ${row['salary_max']}

    Employers:
    {', '.join(row['companies'])}

    """

    documents.append(doc)

for i, doc in enumerate(documents):
    if len(doc.split()) > 5000:
        print(i, len(doc.split()))

response = client.embeddings.create(
    model="text-embedding-3-small",
    input=documents
)

vectors = [
    item.embedding
    for item in response.data
]


with open("role_embeddings.pkl", "wb") as f:
    pickle.dump(
        {
            "documents": documents,
            "vectors": vectors,
            "roles": jobs["title_clean"].tolist()
        },
        f
    )